### ISSUE TITLE
Website example not working.

### ISSUE THREAD

**Issue by Felix-Petersen** [f-dangel/backpack#223]
Hi, 

the examples (diagonal and KFAC) on the website (https://backpack.pt/) are not working. I believe they are meant for a prior version.

Best 
Felix

**Comment by f-dangel** [comment]
Hi,

thanks for reporting this problem (related to https://github.com/fKunstner/backpack-discuss/issues/65). I confirm the mentioned example does not work. 

Check out [this](https://docs.backpack.pt/en/master/basic_usage/example_all_in_one.html) example which should work.

**Comment by f-dangel** [comment]
Fixed by #298. Closing.
