### ISSUE TITLE
Update examples on website

### ISSUE THREAD

**Issue by Niccolo-Ajroldi** [f-dangel/backpack#261]
I have seen that the examples on the official website (https://backpack.pt/), are not up to date with the current configuration of the library.

`from backpack import extend, backpack, Variance`

should be substituted with

`from backpack import extend, backpack`
`from backpack.extensions import Variance`

And the same for the other examples. It's an easy thing, but I was struggling with ImportErrors when trying to run the example codes.

**Comment by f-dangel** [comment]
Hi,

thanks for expressing this inconsistency. I pushed an [improvement](https://github.com/f-dangel/backpack/pull/262) that fixes the incorrect imports from BackPACK on the website once it is merged to `master`.

For the correct import, replace:

- `from backpack import ..., X` <-> `from backpack import ..., extensions`
- `with backpack(X())` <-> `with backpack(extensions.X())`

Note that the examples still won't run out of the box, as the data loading function is pseudocode.
