### ISSUE TITLE
Conv2d derivative issues

### ISSUE THREAD

**Issue by joshromoff** [f-dangel/backpack#30]
It seems like:

https://github.com/f-dangel/backpack/blob/03db23fd796dfec2069996bd44ac08c4988ebbf8/backpack/core/derivatives/conv2d.py#L198

only works for certain stride/padding/kernel/dilation combos and can return an incompatible shape with:

https://github.com/f-dangel/backpack/blob/03db23fd796dfec2069996bd44ac08c4988ebbf8/backpack/core/derivatives/conv2d.py#L201

From my testing, it works when "in + 2 * padding - dilation * (kernel - 1) - 1" is a multiple of the stride, i.e, when there is no rounding down from the floor operation in the forward pass of the conv2d.

**Comment by fKunstner** [comment]
Good catch, thanks for the report! 👍

I pushed [a fix](https://github.com/f-dangel/backpack/pull/31), it should find its way to a release soon. You can try it by installing from this branch,
`pip install git+https://github.com/f-dangel/backpack.git@issue30`

**Comment by f-dangel** [comment]
Thanks for reporting @joshromoff,
does this fix your problem?

**Comment by joshromoff** [comment]
yup! that fixed it. thanks!
