### ISSUE TITLE
add support for torch 2.0? 

### ISSUE THREAD

**Issue by yahui624** [f-dangel/backpack#303]
hi, right now it has a limitation of `satisfies the requirement torch<1.13.0,>=1.9.0 (from backpack-for-pytorch)`. Will you be adding support for torch2.0 soon?

**Comment by f-dangel** [comment]
Hi, 

thanks for your question. To the best of my knowledge, `torch 2.0` is fully backward-compatible with `1.xx`, but introduces a new `compile` function. So in principle, BackPACK should support `2.0`. The reason we do not officially support `2.0` is that we have not tested how `compile` interferes with the forward and full backward hooks that BackPACK uses under the hood.

If you run into issues while using BackPACK with `torch 2.0`, please let us know.

Best,
Felix

**Comment by yahui624** [comment]
Hi, 
i m experimenting my model on nvidia h100/sm 90, which requires pytorch to build from source. inside that conda environment, i do pip install pip install backpack-for-torch, it will auto degrade my torch version to 1.13, how can i stop that from happening?

**Comment by f-dangel** [comment]
Hi,

you can `pip install backpack-for-pytorch` first, then `pip uninstall torch` and install the PyTorch by building locally.

**Comment by yahui624** [comment]
awesome thanks!

**Comment by hlzl** [comment]
@f-dangel I can confirm from my testing that it works with `torch 2.0.1`. 
However, using `pip` to install `backpack` now automatically downgrades your `torch` version to `1.13.0`, which is kind of annoying.
It would thus be great if you could change the requirement to `torch>=1.9.0` or `torch<2.1.0,>=1.9.0` as an intermediate solution.

**Comment by hlzl** [comment]
Ah sorry, seems like I downloaded it just before the bump to `1.6.0`. Thanks for letting me know!
