### ISSUE TITLE
torch version < 2.x in `setup.cfg`

### ISSUE THREAD

**Issue by elcorto** [f-dangel/backpack#310]
Hi

Thanks for the nice library. I'm using it via [laplace](https://github.com/AlexImmer/Laplace).

I wonder why `setup.cfg` says

```
install_requires =
    torch >= 1.9.0, < 2.0.0
```

while #307 gives the impression that torch 2.x is supported.

This makes the install a bit bumpy and maybe others have encountered this as well. One usually has a pre-installed torch (say on an HPC system) that e.g. `pip` picks up rather than pulling a pypi version of the latter. When `torch >= 1.9.0, < 2.0.0` and we expose an existing torch 2.x, the install will still pull an older torch 1.x from pypi. The solution so far is to install all dependencies manually and then `pip install --no-deps` this package.

Thanks a lot.

**Comment by f-dangel** [comment]
Hi,

thanks for bringing this up. This should be resolved with #309. I will prepare a new release that supports `torch2.x`. An immediate fix would be to install from this repository's `development` branch, which already contains the requirement update.

Best,
Felix

**Comment by elcorto** [comment]
OK, thanks for the quick answer. I was a bit puzzled since the commit (7264532) of #307 is in master (ffa6068) and I was using that. But I just saw that the later bfb1fde introduces the line in question.
