### ISSUE TITLE
try_view is unnecessary since pytorch 1.4.0

### ISSUE THREAD

**Issue by SsnL** [f-dangel/backpack#47]
When a `view` can be performed, `reshape` essentially does a `view`. The backward pass used to be less efficient, but that has been fixed in pytorch 1.4.0 (by https://github.com/pytorch/pytorch/pull/28901).

https://github.com/f-dangel/backpack/blob/3122de062d5bbcdcba8f8e02d24adb1bd2cdada6/backpack/utils/ein.py#L175-L180

**Comment by f-dangel** [comment]
Hey @SsnL, thanks for pointing that out. We'll add it to the release plan
