### ISSUE TITLE
Support for ConvTranspose2d

### ISSUE THREAD

**Issue by kuc2477** [f-dangel/backpack#48]
I think it would be great to have first order extension supports for ConvTranspose2d as it is widely used in generative models and various vision tasks.

Thanks again for this amazing library!

**Comment by fKunstner** [comment]
Thanks for reaching out! Adding support for more layers is on our todolist, and the ConvTranspose2d is definitely near the top (although it's a bit hard to give a timing estimate in those weird times).

**Comment by f-dangel** [comment]
**Update**: Individual gradients for `ConvTranspose1/2/3d` are now available on `development` [PR](https://github.com/f-dangel/backpack/pull/92/files). You can already try them `with backpack(BatchGrad())` by installing from that branch, in case you don't want to wait for the next release.

**Comment by f-dangel** [comment]
Now in [version `1.2.0`](https://github.com/f-dangel/backpack/tree/1.2.0). Closing
