### ISSUE TITLE
RuntimeError: 'NoneType' object is not subscriptable in backward()

### ISSUE THREAD

**Issue by IAmS4n** [f-dangel/backpack#71]
First of all, thanks for your great lib.
Is `torch.cat` a supported operation in the computation graph? It seems using concatenation in second order extensions cause error in the `backward()`:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-14-427e1d95b045> in <module>
     21 
     22         with backpack(DiagHessian()):
---> 23             loss.backward(create_graph=True,)
     24 

~/anaconda3/lib/python3.7/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    196                 products. Defaults to ``False``.
    197         """
--> 198         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    199 
    200     def register_hook(self, hook):

~/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     98     Variable._execution_engine.run_backward(
     99         tensors, grad_tensors, retain_graph, create_graph,
--> 100         allow_unreachable=True)  # allow_unreachable flag
    101 
    102 

RuntimeError: 'NoneType' object is not subscriptable
```

**Comment by fKunstner** [comment]
Hi Ehsan, thanks for reaching out. 

I don't think concatenation is going to work, as it is not a sequential module. I guess you wrote a forward pass to use this

**Comment by fKunstner** [comment]
Hi Ehsan, thanks for reaching out. 

Can you share a minimal code example to reproduce this? We should improve the error messages. The stack-trace, as it is, makes me think there is a problem with the standard backward pass, regardless of backpack.

But in any case, I don't think concatenation is going to work, as it is not a sequential module. To use a `torch.cat`, I guess you wrote a custom forward pass rather than use a sequential module? This is indeed [not supported](https://docs.backpack.pt/en/master/supported-layers.html#supported-models) for second-order extensions. What is the use-case for the concatenation? Maybe we can recommend a workaround.

**Comment by IAmS4n** [comment]
Thanks for your reply.
Yes, you are right. concatenation was used out of a sequential model. does the code example still required?
I need to apply the same module on two different inputs (one of them is the output of another module). [as described](https://docs.backpack.pt/en/master/good-to-know.html), reusing the same module multiple times in the computation graph is limited. so, my solution was the concatenation of input as the batch dimension. is there any possible solution? or any simple example for adding a new layer to the library?

**Comment by fKunstner** [comment]
> reusing the same module multiple times in the computation graph is limited. so, my solution was the concatenation of input as the batch dimension. [...] simple example for adding a new layer to the library?

Second order information for models with parameter reuse is tricky, and Backpack's second pass uses the assumption that the model is sequential to make things easy. I don't think this could be implemented by just adding a new module in the general case. 

The doc for extending Backpack is still work in progress. It's unlikely, but if your use case can be cast as something that is "simple" for Backpack, that might work. I'm not sure I follow what you are trying to backpropagate through, to. What is the network structure, and what is the goal/application?
