### ISSUE TITLE
Using backpack after a torch.autograd.grad call

### ISSUE THREAD

**Issue by ammunk** [f-dangel/backpack#83]
# Summary

Using backpack with respect to one set of parameters after using `torch.autograd.grad` with respect to a different set of parameters. This may not be easy to implement as I it is a second order extension (a gradient of gradients), but it would be awesome to support something like this.

## Specifics

Considering the following code

```
import torch
import torch.nn as nn
from backpack import backpack, extend
from backpack.extensions import BatchGrad

net = nn.Linear(2,1)

input = torch.randn(5,2, requires_grad=True) + 1

model = extend(net)

parameters = tuple(net.parameters())
out = net(input).pow(2)

# gradient with respect to input
grad_input = torch.autograd(out.sum(), input, create_graph=True)
grad_input = torch.cat([g.flatten(start_dim=1) for g in grad_input])

print(grad_input.shape) # torch.Size([5,2])

# gradients with respect to parameters --- Fails here!
with bachpack(BatchGrad()):
    _ = torch.autograd.grad(grad_input.sum(), parameters, create_graph=True)

print(parameters[0].grad_batch) # <- need this
```

## Traceback

```
Grad size after first autograd torch.Size([5, 2])

Traceback (most recent call last):
  File "grad_tests.py", line 28, in <module>guess
    g = torch.autograd.grad(grad.sum(), parameters1[0], create_graph=True)
  File "path_to_torch/autograd/__init__.py", line 156, in grad
    return Variable._execution_engine.run_backward(
RuntimeError: 'Linear' object has no attribute 'input0'
```

**Comment by MandyXie** [comment]
Did you figure out how to do this? I have the same issue.

**Comment by fKunstner** [comment]
Thanks for the bump! Sadly this feature seems out of reach. It's not just something we can "add" to an existing backward pass. If you need individual gradients of functions of individual gradients, the internals of pytorch might not be flexible enough. It might be possible with Jax's [vmap](https://jax.readthedocs.io/en/latest/jax.html#vectorization-vmap).

**Comment by ammunk** [comment]
I see, thanks :) I'll close this then.
