### ISSUE TITLE
Support on torch.nn.DataParallel for multiple GPUs training

### ISSUE THREAD

**Issue by YiifeiWang** [f-dangel/backpack#86]
I try to use backpack to calculate the batched gradient of a medium size neural network on two gpu. I use the following code to construct the net.

net = extend(net)
net = torch.nn.DataParallel(net)
net.to('cuda')

However, in practice, I encounter the following error.

RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1

If it is possible, would you mind add a toy example on how to use backpack with multiple GPUs along with torch.nn.DataParallel? This will be very helpful.

**Comment by fKunstner** [comment]
Hi Yifei, thanks for reaching out.

I am not familiar with the parallelism part of PyTorch, but my first guess is that backpack is not going to play along nicely with it. Things that are likely to break is how we're storing the results of the backpack extensions and how hooks are called by PyTorch. I don't have a multi-gpu machine on hand to try it out at the moment, but we'll add it to the todo list of potential features.

**Comment by YiifeiWang** [comment]
Hi Dangel,

Thanks for the quick response. Hope that this feature will be implemented sooner.
